apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./cert-manager/ks.yaml
components:
- ../../components/namespace
configMapGenerator:
- name: namespace-config
  literals:
  - namespace=cert-manager
