# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-filesystem
