# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
  namespace: observability
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: pushover
            repeat_interval: 12h
            routes:
              - receiver: heartbeat
                group_interval: 5m
                group_wait: 0s
                matchers:
                  - alertname =~ "Watchdog"
                repeat_interval: 5m
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: jira
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          receivers:
            - name: heartbeat
              webhook_configs:
                - send_resolved: true
                  url: "{{ .ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_URL }}"
            - name: "null"
            - name: jira
              opsgenie_configs:
                - send_resolved: true
                  update_alerts: true
                  api_key: {{.JIRA_OPSGENIE_API_KEY}}
  dataFrom:
  - extract:
      key: alertmanager
  - extract:
      key: jira-opsgenie
