# trunk-ignore-all(trunk-yls/no-yls)
area/bootstrap:
- changed-files:
  - any-glob-to-any-file: bootstrap/**/*
area/docs:
- changed-files:
  - any-glob-to-any-file:
    - "docs/**/*"
    - "README.md"
area/ci:
- changed-files:
  - any-glob-to-any-file: .github/**/*
area/k8s:
- changed-files:
  - any-glob-to-any-file: kubernetes/**/*
area/task:
- changed-files:
  - any-glob-to-any-file: .taskfiles/**/*
  - any-glob-to-any-file: Taskfile*
area/trunk:
- changed-files:
  - any-glob-to-any-file: .trunk/**/*
