# yaml-language-server: $schema=https://json.schemastore.org/github-release-config.json
changelog:
  exclude:
    labels:
    - type/digest
  categories:
  - title: Kubernetes
    labels:
    - area/kubernetes
  - title: Bootstrap
    labels:
    - area/bootstrap
  - title: Docs
    labels:
    - area/docs
  - title: Taskfile
    labels:
    - area/taskfile
  - title: GitHub
    labels:
    - area/ci
  - title: Trunk
    labels:
    - area/trunk
  - title: Massive Changes
    labels:
    - size/xxl
    - size/xl
  - title: Large Changes
    labels:
    - size/l
  - title: Medium Changes
    labels:
    - size/m
  - title: Small Changes
    labels:
    - size/s
    - size/xs
  - title: Other Changes
    labels:
    - "*"
