# yaml-language-server: $schema=https://json.schemastore.org/github-release-config.json
changelog:
  exclude:
    labels:
    - type/digest
  categories:
  - title: Kubernetes
    labels:
    - area/kubernetes
  - title: Bootstrap
    labels:
    - area/bootstrap
  - title: Docs
    labels:
    - area/docs
  - title: Taskfile
    labels:
    - area/taskfile
  - title: GitHub
    labels:
    - area/github
  - title: Trunk
    labels:
    - area/trunk
  - title: Other Changes
    labels:
    - "*"
