# yaml-language-server: $schema=https://json.schemastore.org/github-release-config.json
changelog:
  exclude:
    authors:
    - renovate
    labels:
    - type/digest
  categories:
  - title: Major Updates
    labels:
    - type/major
  - title: Minor Updates
    labels:
    - type/minor
  - title: Other Changes
    labels:
    - "*"
