# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-namespace
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  components:
  - ../../components/namespace
  postBuild:
    substitute:
      NAMESPACE: rook-ceph
      VOLSYNC_PRIVILEGED_MOVERS: "true"
