# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config-json
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: docker-config-json
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .DOCKER_REGISTRY | lower }}":{"username":"{{ .DOCKER_USER }}","password":"{{ .DOCKER_PASSWORD }}","auth":"{{ printf "%s:%s" .DOCKER_USER .DOCKER_PASSWORD | b64enc }}"}}}'
  dataFrom:
  - extract:
      key: docker-config
