# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghar-set-zoo
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: ghar-controller
    namespace: actions-runner-system
  values:
    nameOverride: ghar-set-zoo
    runnerScaleSetName: ghar-set-zoo
    githubConfigSecret: actions-runner-controller-auth-secret
    githubConfigUrl: https://github.com/kflix-tv
    minRunners: 2
    maxRunners: 12
    containerMode:
      type: dind
    template:
      spec:
        containers:
        - name: runner
          annotations:
            reloader.stakater.com/auto: "true"
          image: ghcr.io/kflix-tv/actions-runner:2.317.0@sha256:f05a3e263d66ff0065143d07480200d310d469650283b805de986d44775412ae
          command: ["/home/runner/run.sh"]
          volumeMounts:
          - name: docker-config-json
            mountPath: /home/runner/.docker/config.json
            subPath: config.json
            readOnly: true
        volumes:
        - name: docker-config-json
          secret:
            secretName: docker-config-json
            secretNamespace: actions-runner-system
            items:
            - key: .dockerconfigjson
              path: config.json
    controllerServiceAccount:
      name: ghar-controller
      namespace: actions-runner-system
