# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: thanos
spec:
  refreshInterval: 1h
  secretStoreRefs:
  - name: op-secret-store
    kind: ClusterSecretStore
  selector:
    secret:
      name: thanos-bucket
  data:
  - match:
      secretKey: &key AWS_ACCESS_KEY_ID
      remoteRef:
        remoteKey: thanos
        property: *key
  - match:
      secretKey: &key AWS_SECRET_ACCESS_KEY
      remoteRef:
        remoteKey: thanos
        property: *key
