# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
