# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
  namespace: flux-system
spec:
  targetNamespace: arrs
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: external-secrets-secret-store
  path: ./kubernetes/apps/arrs/sabnzbd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sab
