# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ghar-zoo
  namespace: flux-system
spec:
  targetNamespace: actions-runner-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: ghar-controller
  path: ./kubernetes/apps/actions-runner-system/ghar-scale-set/arc-zoo
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
