# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: "${SECRET_DOMAIN/./-}-production-tls"
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "network/${SECRET_DOMAIN/./-}-production-tls"
