apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatus
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
# yamllint disable-line rule:document-start
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatus
  annotations:
    ignore-check.kube-linter.io/access-to-secrets: "Gatus needs access to secrets"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatus
subjects:
- kind: ServiceAccount
  name: gatus
  namespace: observability
