# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .github_app_id }}"
        github_app_installation_id: "{{ .github_app_installation_id }}"
        github_app_private_key: "{{ .github_app_private_key | b64dec  }}"
  dataFrom:
  - extract:
      key: actions-runner-controller
