# yaml-language-server: $schema=https://k8s-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: alert-manager
  namespace: _placeholder # Placeholder for replacement
spec:
  providerRef:
    name: alert-manager
  eventSeverity: error
  eventSources:
  - kind: HelmRelease
    name: "*"
  exclusionList:
  - "error.*lookup github\\.com"
  - "error.*lookup raw\\.githubusercontent\\.com"
  - "dial.*tcp.*timeout"
  - "waiting.*socket"
  suspend: false
