apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: ${VOLSYNC_PRIVILEGED_MOVERS:-"false"}
