apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: namespace-replacement
replacements:
- source:
    kind: ConfigMap
    name: namespace-config
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
  - select:
      kind: Alert
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Provider
    fieldPaths:
    - metadata.namespace
