# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/persistentvolumeclaim-v1.json
# TODO: Move to volsync template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph-block
