# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/clusterrolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor
subjects:
- kind: ServiceAccount
  name: capacitor
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: capacitor
  apiGroup: rbac.authorization.k8s.io
