# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.100.0.0/16"
