apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:JPvqeVOsYWOK0mb5L8a8PssYhr0vxtYq0hm82bU53h8=,iv:QBWCs8ZlDk9aAaYZV7mwuEXZvQX649pf2Wq7vIApWn8=,tag:0wgwB5CBjdOqpC3n8Ev+nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDFtWHRDTHZreFl2YURZ
            NTBCK1BBamVQKzdONkt3SHluN080MEs5MG5nCkJvYXB0Z0NHL2hQa2xkdS8vMGVV
            ZE53R1pjVmRrd3IzT3NySXBmUnhRMzQKLS0tIEVRbXU1aG44QkkyMGx2enZiZnhl
            alYvNm5KcjhacUNPR3JtUUpLWnZsK2sKAjxvWdWWIJAYjv2w62B+ntSKSecEeRtu
            mGzpglWx8t+nMX6z3Z8b2B8OTr7JLjpNZdjG3NxGqBRKWo9U6iPznw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T02:32:14Z"
    mac: ENC[AES256_GCM,data:zvRCzyvPxL8HU6ZOTSxAaFQP0HoJm6XmxOUt/BwkCV9zWqMaI2HIAM7WDh76IskNWJX1DqirZn9I5/SrX+uxFWzaNtaMzex5DoclIeYR/EhP+/3Skmz6209rb8Nd9S9lIiYIdkcjMAY/cugHBLhF32Ig6K0f6auV5+wFg80NgVI=,iv:CkfVoJ1eG3JhxRrd+JBYZvkwHXYoAQt6gGyUxIrsgyM=,tag:iGtl+P2oMs55C0dSQC+4uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
