# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:

  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
    - for: {var: resource}
      cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
    - {msg: "Missing kubeconform script", sh: "test -f {{.KUBECONFORM_SCRIPT}}",}

  .reset:
    internal: true
    cmd: rm -rf {{.KUBERNETES_DIR}}

  staging:
    desc: Switch cluster to Staging LE Certs
    cmds:
    - sed -i 's/production/staging/g' kubernetes/apps/network/ingress-nginx/certificates/kustomization.yaml
    - git add kubernetes/apps/network/ingress-nginx/certificates/kustomization.yaml
    - sed -i 's/production/staging/g' kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml
    - git add kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml
    - sed -i 's/production/staging/g' kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml
    - git add kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml
    - 'git commit -m "fix(kubernetes): Staging TLS"'

  production:
    desc: Switch cluster to Staging LE Certs
    cmds:
    - sed -i 's/staging/production/g' kubernetes/apps/network/ingress-nginx/certificates/kustomization.yaml
    - git add kubernetes/apps/network/ingress-nginx/certificates/kustomization.yaml
    - sed -i 's/staging/production/g' kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml
    - git add kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml
    - sed -i 's/staging/production/g' kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml
    - git add kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml
    - 'git commit -m "fix(kubernetes): Production TLS"'

  webhook:
    desc: Print out the Webhook URL for github
    cmd: kubectl -n flux-system get receiver github-receiver -o jsonpath='{.status.webhookPath}'

  webhook-secret:
    desc: Print out the Webhook Secret for github
    cmd: kubectl -n flux-system get secret github-webhook-token-secret -o jsonpath='{.data.token}' | base64 --decode
