# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./externalsecret.yaml
- ./pvc.yaml
- ./helmrelease.yaml
- ../../../../templates/gatus/guarded
configMapGenerator:
- name: bazarr-scripts
  files:
  - post-process.sh=./scripts/post-process.sh
configurations:
- ./patches/kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true
