# TODO: Move to volsync template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: ceph-block
