# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts/
      chart: reflector
      version: 7.1.262
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
      interval: 5m
