# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Flux Kustomization Sync"

on:
  push:
    branches: ["main"]
    paths: ["kubernetes/network/**", "kubernetes/registry/**"]

jobs:
  sync:
    name: Flux Kustomization Sync
    runs-on: ["ghar-set-zoo"]
    strategy:
      matrix:
        cluster: ["network", "registry"]
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: "${{ secrets.BOT_APP_ID }}"
        private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        token: "${{ steps.app-token.outputs.token }}"

    # - name: Setup Homebrew
    #   uses: Homebrew/actions/setup-homebrew@master

    # - name: Setup Workflow Tools
    #   shell: bash
    #   run: brew install fluxcd/tap/flux

    - name: Write kubeconfig
      id: kubeconfig
      uses: timheuer/base64-to-file@v1
      with:
        encodedString: "${{ secrets.KUBECONFIG }}"
        fileName: kubeconfig

    - name: Sync Kustomization
      env:
        KUBECONFIG: "${{ steps.kubeconfig.outputs.filePath }}"
      shell: bash
      run: |
        flux \
            --context "${{ matrix.cluster }}" \
            --namespace flux-system \
            reconcile ks cluster \
            --with-source
