# yaml-language-server: $schema=https://k8s-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
  - start: "${IPAM_LB_RANGE_START}"
    stop: "${IPAM_LB_RANGE_END}"
