# yaml-language-server: $schema=https://k8s-schemas.pages.dev/cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
  namespace: kube-system
spec: # CiliumBGPPeeringPolicySpec
  virtualRouters: # []CiliumBGPVirtualRouter
  - localASN: 65001
    exportPodCIDR: true
    serviceSelector:
      matchExpressions:
      - {key: "helm.toolkit.fluxcd.io/name", operator: In, values: ["adguard-home"]}
    neighbors:
    - peerAddress: ${IPAM_IP_GATEWAY}/32
      peerASN: 65000
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
